title: Paolo Gandini
description: Personal site of Paolo Gandini - INFN Milano
theme: just-the-docs
url: https://pgandini.github.io/paologandini/
logo: "/assets/images/PG.png"
favicon_ico: "/assets/images/favicon.ico"

######################################################
# Aux links for the upper right navigation
aux_links:
  "LHCb":
    - "https://lhcb-outreach.web.cern.ch/"
    - "https://web.infn.it/lhcb_milano/"
  "CERN":
    - "https://home.cern/"
    
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
######################################################

plugins:
  - jekyll-default-layout
