title: Paolo Gandini
description: Personal site of Paolo Gandini - INFN Milano
theme: just-the-docs
url: https://pgandini.github.io/paologandini/
logo: "/assets/images/PG.png"
favicon_ico: "/assets/images/favicon.ico"
color_scheme: gandini

######################################################
# Aux links for the upper right navigation
aux_links:
  "INFN":
    - "https://home.infn.it/it/"
  "CERN":
    - "https://home.cern/"
  "LHCb":
    - "https://lhcb-outreach.web.cern.ch/"
    
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
######################################################
# Social links
social: true
linkedin_url: https://www.linkedin.com/in/paolo-gandini-04a47a18
instagram_url: https://www.instagram.com/paologandini/
######################################################

plugins:
  - jekyll-default-layout
